telegram:
  api_id: 26211891
  api_hash: ff636454c14e4e9527eccaba71742c33
  channels:
    - ZemenExpress
    - nevacomputer
    - meneshayeofficial
    - ethio_brand_collection
    - Leyueqa
    - Shewabrand
    - helloomarketethiopia
